### ISSUE TITLE
mod manager using CMD prtompts blue screened pc needed to reset

### ISSUE THREAD

**Issue by TheJacken** [MythicManiac/MythicModManager#14] opened 2019-04-30 22:38 UTC
after installing the mod manager and some mods, playing for a bit and then restarting caused my computer to CRITICAL_PROSSES_DIED blue screen, in between the last time i restarted and when the blue screen happened this was the only thing i downloaded.

im assuming im the only one to have this happen but i feel like its worth me saying non the less

**Comment by MythicManiac** [comment] 2019-05-01 17:45
It's likely to be a mod doing this, in fact I believe there is a mod that causes blue screen on purpose.

The manager itself should not do anything that causes issues for Windows, it basically just extracts zip files and moves them around. The mods however are a different matter.

Closing this issue as I don't believe it's directly caused by MMM

**Closed by MythicManiac** 2019-05-01 17:45 UTC
